### ISSUE TITLE
HydroOJ新版本无法使用

### ISSUE THREAD

**Issue by laoshuikaixue** [liyanqwq/hydrooj-pastebin-plus#2]
如题，在Hydro 4.13.0 / UI 4.51.0中 出现了插件加载报错的情况
![1d7940230e0b3111c8a25e44765f21f6](https://github.com/liyanqwq/hydrooj-pastebin-plus/assets/79132480/67a0eefd-67b7-429d-bbf6-3c9af597dcbf)

**Comment by ghost** [comment]
qp

**Comment by ghost** [comment]
zc

**Comment by ghost** [comment]
+1
